spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/analysisdata?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#  redis:
#    database: 0
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password:
#    # 连接超时时间（毫秒）
#    timeout: 5000


server:
  servlet:
    context-path: /
  port: 8080


mybatis-plus:
  configuration:
    # 开启下划线转驼峰命名规则
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

